import type { Metadata } from "next";
import { Inter , Nanum_Brush_Script } from "next/font/google";
import "./globals.css";
import NavBarMobile from "@/Components/Header/NavBarMobile";
import NavBarMidScreen from "@/Components/Header/NavBarMidScreen";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
const nanum_brush_script  = Nanum_Brush_Script({
  weight: "400",
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nanum_brush_script',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.style} ${nanum_brush_script.variable}`}>
      <NavBarMobile/>
      <NavBarMidScreen/>
        {children}</body>
    </html>
  );
}
